### ISSUE TITLE
FTP Client issues

### ISSUE THREAD

**Issue by abdesamie** [pReya/ftpServer#2]
Good to find finally an ftp server that supports basic standard ftp commands ! Unfortunately, after successful connection all commands raise the bellow exception, could you please update the readme with how to use it by windows ftp client for example?

![image](https://user-images.githubusercontent.com/32249499/111388213-2c908680-86af-11eb-83b5-168ee23e9671.png)

I tried also using an ftp client (GUI) but it does not work ? does need more implementations?

**Comment by pReya** [comment]
@abdesamie It seems like you're connecting via IPv6 (see output behind EPRT). As stated in the readme: IPv6 is not supported.

Also stated in the readme: GUI clients not supported, because they need a different folder listing format.

**Comment by abdesamie** [comment]
Thanks for your reply @pReya , indeed readme was mentioning that ! i wanted that may be the readme can be enriched of some use cases (commands) , do you know how to enforce FTP over IPV4 on Windows client ? otherwise any tips on successfully submitting ftp request to that server

**Comment by pReya** [comment]
Yes, you're probably right. The readme should contain some example invocations on how to connect with the server. Unfortunately it would take me quite a while to figure this out again. I haven't touched the code in 4 years, and I haven't written a single line of Java since then. Also I don't have a Windows PC, so I'm afraid I can't help with the IPv6 thing. You'll probably have to diasble it globally.

If you figure it out, feel free to create a PR and add the examples to the readme. I'd be happy to merge it.
